services:
    react-native-swinggo:
        build: .
        ports:
            - '8081:8081'
        volumes:
            - .:/app
        command: npx expo start --tunnel --port 8081
        environment:
            - EXPO_DEVTOOLS_LISTEN_PORT=8081
        container_name: react-native-swinggo
        stdin_open: true
        tty: true
        networks:
            - swinggo_network

networks:
    swinggo_network:
        driver: bridge
        name: swinggo_network
